### ISSUE TITLE
Logo Proposal

### ISSUE THREAD

**Issue by Tobaloidee** [itzmeanjan/locate#1]
Hi @itzmeanjan  just finished my design for this project and here it is..

-combination of 3 elements namely Flutter-Android-Location

![LOCATE-01](https://user-images.githubusercontent.com/36028424/57344908-98cd0580-717b-11e9-960b-08933d992b3f.png)

**Comment by itzmeanjan** [comment]
I definitely like this logo :smile: 

Atleast the dart mode added version is awesome .

I'm updating this repo and example app look with a few hours, please take a look at new screenshots and if you think some addition to design, feel free to do so and submit a PR.

**Comment by Tobaloidee** [comment]
Surely I will check the update 😀

**Comment by itzmeanjan** [comment]
Hei @Tobaloidee , I've pushed new look for this app. Take a look [here](https://github.com/itzmeanjan/locate/tree/master/example).

**Comment by Tobaloidee** [comment]
I just changed the colors.. I made 2 versions for you to choose from who's going to be the main logo

![PRES-01](https://user-images.githubusercontent.com/36028424/57420816-d3967280-723b-11e9-8a52-a9998550887c.png)

mock up

![mock](https://user-images.githubusercontent.com/36028424/57420960-5dded680-723c-11e9-9d36-6c1655405fb5.png)

**Comment by itzmeanjan** [comment]
Wow looks nice, *cyanAccent* color is great :heart:.

I think that should be main logo.

And could you also make app icons, so that I can rebuild app with new icons ?

**Comment by Tobaloidee** [comment]
Will do! 👍😊

**Comment by Tobaloidee** [comment]
Here's the PR #2 with the logo, app icons and readme update @itzmeanjan 

other downloadable version & files [HERE](https://drive.google.com/drive/u/1/folders/1vE6R9UV4rQ0RJn2ll0MGLmQu2xFiOGJn)

**Comment by itzmeanjan** [comment]
Hei @Tobaloidee , merging done :relaxed: .

Great work. Hope to have you as designer in next project too. 

Till then :wave:

**Comment by Tobaloidee** [comment]
Surely I will check all your project for logos! Thanks!!
